/***
 * This file is used to generate the topology map from the instance clouds generated by scannet_plt_map.cpp
 * The map will be saved into a json file
 * Note the features are randomly filled and should be corrected by running get_fused_object_features.cpp
 * Author: Clarence Chen
 */


#include "ptc_operations.h"
#include <Eigen/Geometry>

#include <random>
#include <fstream>
#include <sstream>
#include <unordered_map>
#include <iostream>
#include <set>
#include <vector>
#include <filesystem>

#include "topology_map.h"
#include "utils.h"

#define BACKWARD_HAS_DW 1
#include "backward.hpp"
namespace backward{
    backward::SignalHandling sh;
}


// Generate a random 256D embedding vector
Eigen::VectorXf randomEmbedding(int dim = 256) {
    static std::mt19937 gen(std::random_device{}());
    static std::uniform_real_distribution<float> dis(0.0f, 1.0f);
    Eigen::VectorXf vec(dim);
    for (int i = 0; i < dim; ++i) vec[i] = dis(gen);
    return vec;
}

Eigen::VectorXf zeroEmbedding(int dim = 256) {
    Eigen::VectorXf vec(dim);
    vec.setZero();
    return vec;
}

// Load instance_id to name map from CSV
std::unordered_map<int, std::string> loadNameMap(const std::string& csv_file) {
    std::unordered_map<int, std::string> map;
    std::ifstream file(csv_file);
    std::string line;
    std::getline(file, line); // skip header
    while (std::getline(file, line)) {
        std::stringstream ss(line);
        std::string id_str, name;
        std::getline(ss, id_str, ',');
        std::getline(ss, name);
        // Remove "\r" from the end of the name
        name.erase(std::remove(name.begin(), name.end(), '\r'), name.end());
        map[std::stoi(id_str)] = name;
    }
    return map;
}

// Load instance_id to bert embedding map from json
std::unordered_map<int, Eigen::VectorXf> loadBertEmbedding(const std::string& json_file) {
    std::ifstream file(json_file);
    nlohmann::json json;
    file >> json;
    std::unordered_map<int, Eigen::VectorXf> bert_embedding_map;

    // Handle the case where json is an array of feature objects
    if (json.is_array()) {
        for (const auto& item : json) {
            if (item.contains("instance_id") && item.contains("feature")) {
                int instance_id = item["instance_id"];
                const auto& feature_array = item["feature"];
                Eigen::VectorXf feature_vector(feature_array.size());   
                for (size_t i = 0; i < feature_array.size(); ++i) {
                    feature_vector[i] = feature_array[i];
                }
                bert_embedding_map[instance_id] = feature_vector;
            }
        }
    }
    else if (json.is_object()) {
        for (const auto& [id_str, feature] : json.items()) {
            int instance_id = std::stoi(id_str);
            if (feature.is_array()) {
                Eigen::VectorXf feature_vector(feature.size());
                for (size_t i = 0; i < feature.size(); ++i) {
                    feature_vector[i] = feature[i];
                }
                bert_embedding_map[instance_id] = feature_vector;
            }
        }
    }
    else {
        std::cout << "Warning: Bert embedding json is not an array of feature objects or simple object format" << std::endl;
    }

    return bert_embedding_map;
}

// Load visual feature json
std::unordered_map<int, Eigen::VectorXf> loadVisualFeature(const std::string& json_file) {
    std::ifstream file(json_file);
    nlohmann::json json;
    file >> json;
    std::unordered_map<int, Eigen::VectorXf> visual_feature_map;
    
    // Handle the case where json is an array of feature objects
    if (json.is_array()) {
        for (const auto& item : json) {
            if (item.contains("instance_id") && item.contains("feature")) {
                int instance_id = item["instance_id"];
                const auto& feature_array = item["feature"];
                Eigen::VectorXf feature_vector(feature_array.size());
                for (size_t i = 0; i < feature_array.size(); ++i) {
                    feature_vector[i] = feature_array[i];
                }
                visual_feature_map[instance_id] = feature_vector;
            }
        }
    }
    // Handle the case where json is an object with instance_id as keys (simple format)
    else if (json.is_object()) {
        for (const auto& [id_str, feature] : json.items()) {
            int instance_id = std::stoi(id_str);
            if (feature.is_array()) {
                Eigen::VectorXf feature_vector(feature.size());
                for (size_t i = 0; i < feature.size(); ++i) {
                    feature_vector[i] = feature[i];
                }
                visual_feature_map[instance_id] = feature_vector;
            }
        }
    }
    else {
        std::cout << "Warning: Visual feature json is not an array of feature objects or simple object format" << std::endl;
        std::cout << "Will use zero embeddings for visual features" << std::endl;
        return std::unordered_map<int, Eigen::VectorXf>();
    }

    // Print the visual_feature_map
    std::cout << "Loaded " << visual_feature_map.size() << " visual features" << std::endl;
    for (const auto& [id, feature] : visual_feature_map) {
        std::cout << "Instance " << id << " feature dim: " << feature.size() << std::endl;
    }
    
    return visual_feature_map;
}


// Find nearby pairs by grid search to accelerate the edge generation
std::vector<std::pair<int, int>> findNearbyPairs(
    const std::vector<int>& instance_ids,
    const std::unordered_map<int, InstanceInfo>& info_map,
    float edge_threshold) {
    
    std::vector<std::pair<int, int>> nearby_pairs;
    
    // Simple grid-based spatial partitioning
    float cell_size = edge_threshold * 2.0f; // Ensure adjacent cells are checked
    std::unordered_map<std::string, std::vector<int>> grid;
    
    // Assign instances to grid cells
    for (int id : instance_ids) {
        if (info_map.find(id) == info_map.end()) continue;
        const auto& info = info_map.at(id);
        
        int grid_x = static_cast<int>(info.center.x() / cell_size);
        int grid_y = static_cast<int>(info.center.y() / cell_size);
        int grid_z = static_cast<int>(info.center.z() / cell_size);
        
        std::string cell_key = std::to_string(grid_x) + "_" + 
                              std::to_string(grid_y) + "_" + 
                              std::to_string(grid_z);
        grid[cell_key].push_back(id);
    }
    
    // Check instances in same and adjacent cells
    for (const auto& [cell_key, cell_instances] : grid) {
        // Parse cell coordinates
        std::stringstream ss(cell_key);
        std::string x_str, y_str, z_str;
        std::getline(ss, x_str, '_');
        std::getline(ss, y_str, '_');
        std::getline(ss, z_str, '_');
        int grid_x = std::stoi(x_str);
        int grid_y = std::stoi(y_str);
        int grid_z = std::stoi(z_str);
        
        // Check current cell and adjacent cells
        for (int dx = -1; dx <= 1; ++dx) {
            for (int dy = -1; dy <= 1; ++dy) {
                for (int dz = -1; dz <= 1; ++dz) {
                    std::string neighbor_key = std::to_string(grid_x + dx) + "_" +
                                             std::to_string(grid_y + dy) + "_" +
                                             std::to_string(grid_z + dz);
                    
                    if (grid.find(neighbor_key) != grid.end()) {
                        // Check pairs between current and neighbor cells
                        for (int id1 : cell_instances) {
                            for (int id2 : grid[neighbor_key]) {
                                if (id1 >= id2) continue; // Avoid duplicates
                                
                                const auto& info1 = info_map.at(id1);
                                const auto& info2 = info_map.at(id2);
                                float dist = (info1.center - info2.center).norm();
                                
                                if (dist < edge_threshold) {
                                    nearby_pairs.emplace_back(id1, id2);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    return nearby_pairs;
}

// Build topology map
TopologyMap buildTopologyMap(const std::vector<int>& instance_ids,
                               const std::unordered_map<int, InstanceInfo>& info_map,
                               const std::unordered_map<int, std::string>& name_map,
                               const std::unordered_map<int, Eigen::VectorXf>& visual_features,
                               const std::unordered_map<int, Eigen::VectorXf>& bert_features,
                               float edge_threshold = 2.0f) {
    TopologyMap map;
    TopologyMapHypothesis default_hypothesis;

    // Build nodes
    for (int id : instance_ids) {
        if (info_map.find(id) == info_map.end()) continue;
        const auto& info = info_map.at(id);

        // Convert rotation to quaternion
        Eigen::Quaternionf q(info.rotation);
        Orientation orientation{q.x(), q.y(), q.z(), q.w()};

        // Create shape
        auto shape = std::make_shared<OrientedBox>(info.bbox_size.x(), info.bbox_size.y(), info.bbox_size.z(), orientation);

        // Create node
        ObjectNode node;
        node.id = std::to_string(id);
        node.name = name_map.count(id) ? name_map.at(id) : "unknown";
        
        // Use actual visual features if available, otherwise use zero embedding
        if (visual_features.find(id) != visual_features.end()) {
            node.visual_embedding = visual_features.at(id);
        } else {
            std::cout << "Instance " << id << " name: " << node.name << " has no visual feature, using zero embedding" << std::endl;
            node.visual_embedding = zeroEmbedding();
        }

        // Use actual bert features if available, otherwise use zero embedding to represent unknown
        if (bert_features.find(id) != bert_features.end()) {
            node.text_embedding = bert_features.at(id);
        } else {
            std::cout << "Instance " << id << " name: " << node.name << " has no bert feature, using zero embedding" << std::endl;
            node.text_embedding = zeroEmbedding();
        }

        node.shape = shape;
        node.position = info.center;

        map.object_nodes[node.id] = node;
    }

    // Add edges (naive O(n^2))
    std::vector<std::pair<int, int>> nearby_pairs = findNearbyPairs(
        instance_ids, info_map, edge_threshold);

    for (const auto& [id1, id2] : nearby_pairs) {
        Eigen::Vector3f c1 = info_map.at(id1).center;
        Eigen::Vector3f c2 = info_map.at(id2).center;
        float dist = (c1 - c2).norm();
        
        Eigen::Vector3f direction = (c2 - c1).normalized();
        Edge edge;
        edge.source_id = std::to_string(id1);
        edge.target_id = std::to_string(id2);
        edge.distance = dist;
        edge.direction = direction;
        edge.description = "next to";
        std::string edge_id = edge.source_id + "_" + edge.target_id;
        default_hypothesis.edges[edge_id] = edge;
    }

    default_hypothesis.id = "default_hypothesis";
    default_hypothesis.confidence = 1.0f;
    map.edge_hypotheses["default_hypothesis"] = default_hypothesis;
    return map;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "Usage: ./generate_json <path_to_ply> <if_visualize 0 or 1> <use_three_channel_id 0 or 1, default is 0> <edge_threshold, default is 2.0>" << std::endl;
        return -1;
    }

    int int_if_visualize = std::stoi(argv[2]);
    bool if_visualize = int_if_visualize == 1;
    bool use_three_channel_id = false;
    float edge_threshold = 2.0f;

    if (argc == 4) {
        int int_use_three_channel_id = std::stoi(argv[3]);
        use_three_channel_id = int_use_three_channel_id == 1;
    }else if (argc == 5) {
        int int_use_three_channel_id = std::stoi(argv[3]);
        use_three_channel_id = int_use_three_channel_id == 1;
        edge_threshold = std::stof(argv[4]);
    }else if (argc > 5) {
        std::cerr << "Usage: ./generate_json <path_to_ply> <if_visualize 0 or 1> <use_three_channel_id 0 or 1, default is 0> <edge_threshold, default is 2.0>" << std::endl;
        return -1;
    }

    std::cout << "Use three channel id: " << use_three_channel_id << std::endl;
    std::cout << "Edge threshold: " << edge_threshold << std::endl;

    std::string ply_path = argv[1];

    // Substitute "instance_cloud.ply" with "instance_name_map.csv" using std::filesystem
    std::string name_map_path = std::filesystem::path(ply_path).replace_filename("instance_name_map.csv");
    std::string visual_feature_path = std::filesystem::path(ply_path).replace_filename("averaged_instance_features.json");
    std::string bert_feature_path = std::filesystem::path(ply_path).replace_filename("instance_bert_embeddings.json");

    std::cout << "Name map path: " << name_map_path << std::endl;
    std::cout << "Visual feature path: " << visual_feature_path << std::endl;
    std::cout << "Bert feature path: " << bert_feature_path << std::endl;
    // Load instance_id to name map
    CloudT::Ptr cloud(new CloudT);
    if (pcl::io::loadPLYFile<PointT>(ply_path, *cloud) < 0) {
        std::cerr << "Failed to load " << ply_path << std::endl;
        return -1;
    }

    std::vector<int> instance_ids = getInstanceIDs(cloud, use_three_channel_id);
    std::cout << "Instance ids: " << instance_ids.size() << std::endl;
    for (int id : instance_ids) {
        std::cout << id << " ";
    }

    // Map building containers
    std::vector<int> filtered_instance_ids;
    std::unordered_map<int, InstanceInfo> info_map;
    std::unordered_map<int, std::string> name_map;

    // Load name map and show it
    name_map = loadNameMap(name_map_path);
    for (const auto& [id, name] : name_map) {
        std::cout << "Instance " << id << " name: " << name << std::endl;
    }

    // Load visual features
    std::unordered_map<int, Eigen::VectorXf> visual_features;
    try {
        visual_features = loadVisualFeature(visual_feature_path);
        std::cout << "Loaded " << visual_features.size() << " visual features" << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Warning: Failed to load visual features from " << visual_feature_path << ": " << e.what() << std::endl;
        std::cout << "Will use random embeddings for visual features" << std::endl;
    }

    pcl::visualization::PCLVisualizer::Ptr viewer;
    // Load bert features
    std::unordered_map<int, Eigen::VectorXf> bert_features;
    try {
        bert_features = loadBertEmbedding(bert_feature_path);
        std::cout << "Loaded " << bert_features.size() << " bert features" << std::endl;
    } catch (const std::exception& e) {
        std::cerr << "Warning: Failed to load bert features from " << bert_feature_path << ": " << e.what() << std::endl;
        std::cout << "Will use random embeddings for bert features" << std::endl;
    }

    // Visualize the instance clouds
    if (if_visualize) {
        viewer = pcl::visualization::PCLVisualizer::Ptr(new pcl::visualization::PCLVisualizer("Instance Viewer"));
        viewer->setBackgroundColor(0, 0, 0);
        viewer->addPointCloud<PointT>(cloud, "cloud");
        viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 2, "cloud");
    }

    int shape_id = 0;
    for (int id : instance_ids) {
        std::cout << "Instance " << id << std::endl;
        CloudT::Ptr instance = extractInstance(cloud, id, use_three_channel_id);
        CloudT::Ptr inliers1 = filterByClustering(instance);
        CloudT::Ptr inliers2 = removeOutliersMahalanobis(inliers1);

        if (inliers2->size() < 10) continue;

        InstanceInfo info = computeOBB(inliers2);

        // Igonore the instance if size is bigger than 3m
        float size_threshold = 3.0f;
        if (info.bbox_size.x() > size_threshold || info.bbox_size.y() > size_threshold || info.bbox_size.z() > size_threshold) 
        {
            std::cout << "Instance " << id << " is too big, ignored" << std::endl;
            continue;
        }

        // Add to map building containers
        filtered_instance_ids.push_back(id);
        info_map[id] = info;
        name_map[id] = name_map.count(id) ? name_map.at(id) : "unknown"; // in case the name map is not complete

        if (if_visualize) {
            // Create OBB corners in local frame
            Eigen::Vector3f half_size = 0.5f * info.bbox_size;
            std::vector<Eigen::Vector3f> corners_local = {
                {-half_size[0], -half_size[1], -half_size[2]},
                { half_size[0], -half_size[1], -half_size[2]},
                { half_size[0],  half_size[1], -half_size[2]},
                {-half_size[0],  half_size[1], -half_size[2]},
                {-half_size[0], -half_size[1],  half_size[2]},
                { half_size[0], -half_size[1],  half_size[2]},
                { half_size[0],  half_size[1],  half_size[2]},
                {-half_size[0],  half_size[1],  half_size[2]},
            };

            // Transform corners to world coordinates
            std::vector<Eigen::Vector3f> corners_world;
            for (const auto& c : corners_local) {
                corners_world.push_back(info.rotation * c + info.center);
            }

            // Draw box edges
            auto addLine = [&](int i, int j) {
                std::stringstream ss;
                ss << "line_" << shape_id++;
                pcl::PointXYZ p1(corners_world[i][0], corners_world[i][1], corners_world[i][2]);
                pcl::PointXYZ p2(corners_world[j][0], corners_world[j][1], corners_world[j][2]);
                viewer->addLine(p1, p2, 1.0, 0.0, 0.0, ss.str());
            };

            std::vector<std::pair<int, int>> edges = {
                {0,1},{1,2},{2,3},{3,0},
                {4,5},{5,6},{6,7},{7,4},
                {0,4},{1,5},{2,6},{3,7}
            };
            for (auto [i, j] : edges) addLine(i, j);

            // Add center sphere
            pcl::PointXYZ center(info.center[0], info.center[1], info.center[2]);
            std::stringstream ss;
            ss << "center_" << id;
            viewer->addSphere(center, 0.1, 0.0, 1.0, 0.0, ss.str());
        }
    }

    // Build topology map
    TopologyMap map = buildTopologyMap(filtered_instance_ids, info_map, name_map, visual_features, bert_features, edge_threshold);

    if (if_visualize) {
        while (!viewer->wasStopped()) {
            viewer->spinOnce(100);
        }
    }

    // Save topology map to JSON
    std::string json_path = std::filesystem::path(ply_path).replace_filename("topology_map.json");
    map.save(json_path);

    // Test loading the JSON file
    std::cout << "Test loading topology map from " << json_path << std::endl;
    TopologyMap loaded_map;
    loaded_map.load(json_path);

    std::cout << "Loaded topology map from " << json_path << std::endl;
    for (const auto& [id, hypothesis] : loaded_map.edge_hypotheses) {
        std::cout << "Hypothesis " << id << " has " << hypothesis.edges.size() << " edges" << std::endl;
    }
    std::cout << "Object Nodes number: " << loaded_map.object_nodes.size() << std::endl;
    std::cout << "Free space nodes number: " << loaded_map.free_space_nodes.size() << std::endl;

    if (if_visualize) {
        showTopologyMap(loaded_map);
    }


    return 0;
}
